version: '3.8'

services:
        #Descrevendo o serviço do banco de dados
        #1- define o nome do seviço(cada container é tratado como serviço)
        #2- definir imagem que vai utilizar para subir o serviço
        #3- definir nome do container
        #4- porta
        #OBS: todas as instruções que vamos colocar aqui são comando que nós usariamos em um docker run

        banco:
              # o que vem abaixo do serviço é chamado de chave  
              image: mysql:5.7
              container_name: banco
              ports: 
                #mapeando porta do host para porta do container
                     - "3306:3306"
              command: --default-authentication-plugin=mysql_native_password # executando comando dentro do mysql           
              environment:
                #definindo variaveis de ambiente  
                           MYSQL_ROOT_PASSWORD: agenda
                           MYSQL_DATABASE: agenda
                           MYSQL_USER: user
                           MYSQL_PASSWORD: userpassword
              volumes: 
                # mapeando volumes
                       - ./data:/var/lib/mysql  #caso a pasta "data" não exista ela vai ser criada, ela vai servir para guardar os dados das tabelas do mysql, caso destrua o container os dados não vão se perder. (é um atalho para a pasta "mysql" dentro do container.                                           
                       - ./site/pessoa.sql:/docker-entrypoint-initdb.d/pessoa.sql 
                             # copiando o arquivo pessoa.sql para dantro da pasta "docker-entrypoint-initdb.d" esse diretorio executa scripts automaticament
              networks:
                       - site-network                
        web:
              image: nginx:latest
              container_name: aplicacao
              ports:
                       - "8080:80" #seriço do nginx vai estar ouvindo na porta 80 e nós vamos acessas pela porta 8080
              volumes:
                       - ./site:/site # ./ serve para mostrar que a pasta site está no mesmo diretorio que o dockercompose
                       - ./nginx.conf:/etc/nginx/conf.d/default.conf
              networks:
                       - site-network         
        php:
              image: php-pdo
              container_name: php
              volumes:
                       - ./site:/site
              networks:
                       - site-network         
networks:
        site-network:
                   driver: bridge  #tipo da rede 
            
          

